name: Python CI

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install pylint
          pylint testPython.py  # Lint the specific Python file

      - name: Run tests
        run: |
          pip install pytest
          pytest testPython.py --maxfail=1 --disable-warnings -q  # Run tests on the specific Python file

      - name: Build project
        run: |
          # Add build commands here if necessary
          echo "Build step not defined"
